name: quick_contacts_app
description: Quick contacts app with Hive local database
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Storage local (بدل JSON → Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # باش تنجم تلقى مسار التخزين
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # باش نخدم الـ Adapter متاع Contact
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
